### ISSUE TITLE
US9 M3 - Criar método no frontend para cadastrar local na IndicaAi API

### ISSUE THREAD

**Issue by WeillerFernandes** [fga-eps-mds/2018.2-IndicaAi#157]
## Objetivo

Uma vez que o usuário conseguiu visualizar a localização atual dele no mapa, ele deve poder fazer check-in, e os dados do local devem ser cadastrados na IndicaAi API.

## Meta
- [x] Adicionar botão na tela de Cadastrar no Mapa que chame o método que fará o cadastro na IndicaAi API.
- [x] Criar método para comunicar com a IndicaAi API
- [ ] Esse método deve receber as informações:
   - [x] Longitude
   - [x] Latitude
   - [x] Nome
  - [ ] Descrição
- [x] Verificar se há outras informações pertinentes que devem ser passadas.
- [x] Essas informações devem ser passadas por meio de POST para a API IndicaAi, e ao final o local deve estar cadastrado.
- [x] Caso aconteça algum erro durante o processo, uma mensagem deve ser exibida para o usuário.

**Comment by GabrielDVpereira** [comment]
Aqui tem o link da documentação do maps api que pode ajudar 
https://developers.google.com/places/web-service/details
