### ISSUE TITLE
Configurar/Integrar testes no frontend

### ISSUE THREAD

**Issue by WeillerFernandes** [fga-eps-mds/2018.2-IndicaAi#197]
## Objetivo

A proposta é configurar o ambiente de testes no frontend para que a equipe possa testar os métodos que estão sendo implementados no front.

Como o app é desenvolvido em conjunto com outros grupos, é necessário que seja alinhada a comunicação dos grupos para não haver trabalho duplicado. Se algum grupo já estiver desenvolvendo algo semelhante a isso, o nosso objetivo será apenas integrar a nossa parte com os outros grupos. Caso contrário, o nosso objetivo será implementar toda a infraestrutura para tal.

## Metas

- [ ] Configurar o Jest para rodar local
- [ ] Configurar um arquivo .travis.yml para rodar os teste.
- [ ] Subir esse arquivo, após testado, na master do repositório

**Comment by Renatovga2602** [comment]
Conversado com alguns grupos, a princípio não irão implementar testes no frontend.

**Comment by Renatovga2602** [comment]
Por questões de tempo e dificuldade acham overhead
