### ISSUE TITLE
US3 M7 - Submeter as imagens pelo formulário de cadastro

### ISSUE THREAD

**Issue by matheusgomesf** [fga-eps-mds/2018.2-IndicaAi#202]
## Objetivo

As imagens que são carregadas pelo formulário de cadastro devem ser enviadas para a IndicaAi API.

## Metas

- [x] Passar as imagens carregadas no formulário para o método de submissão do cadastro.
- [x] Adicionar as imagens ao content-body da requisição.
- [x] Submeter as imagens pela requisição.
- [x] Ao final, deve ser possível ter acesso a imagem adicionada pela API IndiciaAi.

**Comment by zarbielli** [comment]
Foi visto quer seria mais viável as imagens serem submetidas pela pagína do local ao invés do formulário de cadastro.
