### ISSUE TITLE
TS - Refatorar Buscar Local

### ISSUE THREAD

**Issue by heronsousa** [fga-eps-mds/2018.2-IndicaAi#204]
## Descrição do Problema

Mediante a entrega em da Release, o PR  relacionado a Busca de Locais no frontend foi aceito, para que o produto pudesse ser disponibilizado para teste durante a apresentação da release. Contudo, esse PR trouxe um furo na arquitetura, referente a transição de variáveis entre componentes não estar sendo feita usando Redux.

A solução atual implementada, faz a troca de informação entre componentes por meio da chamada de eventos. Não sendo uma solução muito manutenível e estando fora da arquitetura, propõem-se a refatoração de código.

## Soluções Possíveis

- [ ] Uma possível solução é alterar o código para usar os recursos do Redux, armazenando a variável na `store`.
- [ ] Outra possível solução é reorganizar o código para que essa transição seja feita entre componentes pai e filho, de forma que o filho receba a variável `locals` diretamente pelo `props` .

**Comment by zarbielli** [comment]
Finished! PR at https://github.com/fga-eps-mds/2018.2-FGAPP-FrontEnd/pull/34
@mendesiasmin
