### ISSUE TITLE
Teste de Usabilidade - Favoritar Local

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#211]
### Procedimento
O número de cliques deve ser contado apartir da página inicial do módulo IndicaAi.

### Resultado
- [ ] 1 clique
- [x] 2 cliques
- [ ] 3 cliques
- [ ] 4 cliques
- [ ] 5 ou mais cliques >> A funcionalidade deve ter a lógica de interação repensada.

### Procedimento
Deve-se entregar o app na página inicial do módulo Indica Ai, e deve-se pedir para o usuário realizar a função X no sistema. Não é para o aplicador dar nenhuma informação, ou indicar quais passos o usuário deve indicar, ele deve descobirir sozinho, como forma de testar a intuitividade do app. Ao final da execução da tarefa deve-se pedir que ele avalie em uma escala de 0 a 10 a funcionalidade.

### Resultado
- [ ] 0 a 2  >> A funcionalidade deve ter a lógica de interação repensada.
- [ ] 3 a 5 >> A funcionalidade deve ter a lógica de interação repensada.
- [ ] 6 a 8
- [x] 8 a 10

**Comment by zarbielli** [comment]
Nenhuma reclamação! O coração é intuitivo e assim que visto implica algo no sentindo de gostar assim como é feito no instagram e spotify. A confirmação que o local foi favoritado é bonita e rápida. O fato do coração ficar preenchido com a cor vermelha após acionado tambem confirma que o botão foi pressionado e o local adicionado aos favoritos !
