### ISSUE TITLE
Teste de Usabilidade - Cadastrar Local

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#214]
### Procedimento
O número de cliques deve ser contado apartir da página inicial do módulo IndicaAi.

### Resultado
- [ ] 1 clique
- [ ] 2 cliques
- [x] 3 cliques
- [ ] 4 cliques
- [ ] 5 ou mais cliques >> A funcionalidade deve ter a lógica de interação repensada.

### Procedimento
Deve-se entregar o app na página inicial do módulo Indica Ai, e deve-se pedir para o usuário realizar a função X no sistema. Não é para o aplicador dar nenhuma informação, ou indicar quais passos o usuário deve indicar, ele deve descobirir sozinho, como forma de testar a intuitividade do app. Ao final da execução da tarefa deve-se pedir que ele avalie em uma escala de 0 a 10 a funcionalidade.

### Resultado
- [ ] 0 a 2  >> A funcionalidade deve ter a lógica de interação repensada.
- [ ] 3 a 5 >> A funcionalidade deve ter a lógica de interação repensada.
- [ ] 6 a 8
- [x] 8 a 10

**Comment by zarbielli** [comment]
A questão do teclado está por cima do campo de descrição está ruim, assim como já haviámos averiguado. Foi sugerido um scrollview para a página assim seria possivel rolar a pgina e subir o botão de confirmar cadastro, outra forma de solucionar o problema seria fazer com que o teclado minimizasse sozinho com um clique fora do campo de descrição. 
Foi informado tambem que o icone de adicionar imagens poderia ser um icone com a forma de camera igual ao existente no Instagram ou um icnone que remetesse a galeria pois sua função é abrir a galeria. @heronsousa como você está com a issue de refatorar a página de cadastro se atente a essa informações e tente implementar o scrollview ou fazer com que o teclado se esconda com um click fora do campo de descrição.
