### ISSUE TITLE
Teste de Usabilidade - Visualizar Publicidade

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#216]
### Procedimento
O número de cliques deve ser contado apartir da página inicial do módulo IndicaAi.

### Resultado
- [x] 1 clique
- [ ] 2 cliques
- [ ] 3 cliques
- [ ] 4 cliques
- [ ] 5 ou mais cliques >> A funcionalidade deve ter a lógica de interação repensada.

### Procedimento
Deve-se entregar o app na página inicial do módulo Indica Ai, e deve-se pedir para o usuário realizar a função X no sistema. Não é para o aplicador dar nenhuma informação, ou indicar quais passos o usuário deve indicar, ele deve descobirir sozinho, como forma de testar a intuitividade do app. Ao final da execução da tarefa deve-se pedir que ele avalie em uma escala de 0 a 10 a funcionalidade.

### Resultado
- [ ] 0 a 2  >> A funcionalidade deve ter a lógica de interação repensada.
- [ ] 3 a 5 >> A funcionalidade deve ter a lógica de interação repensada.
- [x] 6 a 8
- [ ] 8 a 10

**Comment by zarbielli** [comment]
Foi relatado que não há muito destaque que diferencie um anuncio de um local qualquer! A palavra anúncio está deslocada no card e deve ser alinhada a esquerda. O fato do anúncio vir antes dos outros cards de locais obriga o usuário a ver os anúncios o que é bom para quem está anúnciando ! Foi sugerido que o card de anuncio sejá mais personalizado para melhorar a diferenciar dos demais locais.
