### ISSUE TITLE
Documentação - Reavaliar a métrica de número de commits

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#223]
## Objetivo

A métrica de número de commits não está sendo totalmente coletada, porque parte do desenvolvimento está no front , e neste repositório há vários times commitando além do Indica Ai. Portanto deve-se traçar outra estratégia para essa métrica, ou substituir essa métrica por outra que demonstre melhor a produtividade da equipe.

## Tópicos

- [ ] Definir nova estratégia de coleta da métrica de Número de Commits ou definir uma nova métrica que acompanhe a produtividade da equipe.

**Comment by heronsousa** [comment]
Após observar algumas métricas de produtividade para times de scrum, não encontrei nenhuma que sirva para nosso contexto. A solução seria redefinir o modo que é realizado a coleta do número de commits. 
Há diversas  ferramentas para análise de repositórios para a coleta desses dados, uma delas é gitential, um site que traz métricas objetivas para medir o processo de desenvolvimento de software, que pode suprir a nossa necessidade.
gitential.com
