### ISSUE TITLE
US5 M3 - Linkar as telas em que um local é exibido para redirecionar para a página de Visualização do Local

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#256]
## Objetivo

Como a parte de visualizar local não estava pronta antes, aconteceu de partes do código que deveriam chamar essa tela serem implementadas, mas não executarem essa ação. Exemplo claro é a tela de buscar, na qual uma lista de locais é renderizada, mas não é possível visualizar o local individualmente. Com esta issue deve-se procurar os locais em que isso ocorra, e fazer a chama do ViewLocal, caso a pessoa clique no local.

## Metas

- [x] Garantir que a pessoa ao clicar em um local, seja redirecionada para a tela de VisualizarLocal.
- [x] O ideal é que isso seja jeito em um único componente, e esse componente seja chamado nos demais locais.
- [x] A id do local que deve ser renderizada deve ser sempre passada por props.
- [x] Verificar as telas que já foram implementadas e deveriam ter esse comportamento. Caso não tenham, corrigí-las.

**Comment by zarbielli** [comment]
https://medium.com/react-native-training/react-native-navigation-v2-by-wix-getting-started-7d647e944132
