### ISSUE TITLE
US3 M5 - Adicionar imagens para o local na API IndicaAi

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#264]
## Objetivo

Um dos requisitos do projeto é o usuário conseguir adicionar imagens ao local. Portanto, esta funcionalidade deve ser implementada no backend.

## Metas

- [x] Pesquisar como funciona para enviar imagens do React para a API Rails.
- [x] Com base na pesquisa, provavelmente uma GEM terá que ser instalada na API. Eu conheço a carrierwave, mas não sei como funciona integrado com o React. Então, verificar as possibilidades, e definir e instalar a gem.
- [x] Configurar a model de tratamento de imagem.
- [x] Adaptar, se necessário, o método de cadastro da controller para receber as imagens.

**Comment by zarbielli** [comment]
@mendesiasmin creio que não precisamos de uma model para tratamento de imagens, pelo que andei pesquisando podemos passar a imagem do front pra API via JSON transformando a imagem em string via base64 que o React Native tem suport através da seguinte biblioteca https://www.npmjs.com/package/react-native-convert-image-to-base64 e o Rails tem nativamente suporte a string de base64. Tendo isso em vista não seria melhor apenas criar uma coluna de imagens na model de Locais ?

**Comment by mendesiasmin** [comment]
@zarbielli, não acho muito interessante a ideia de salvar como uma string na API porque isso pode acabar limitando a gente futuramente a usar alguns recursos, como validar o tamanho da imagem, o tipo do arquivo... Se por acaso nos quisermos definir uma proporção específica para as imagens, de forma que elas se adaptem melhor ao nosso layout, ao invés de deixar livre para o usuário mandar em qualquer proporção, eu sei que a o Rails já oferece gems que auxiliariam nesse tratamento (crop de imagens), mas se tivermos uma string, não sei como isso funcionaria.

**Comment by mendesiasmin** [comment]
@zarbielli dá uma olhada nesse tutorial https://gist.github.com/joemusacchia/fec89ea3360d5d7980b96e2bc6a39710

**Comment by zarbielli** [comment]
Vou testar aqui ! Obrigado @mendesiasmin
