### ISSUE TITLE
US1 - Buscar locais (Frontend)

### ISSUE THREAD

**Issue by GabrielDVpereira** [fga-eps-mds/2018.2-IndicaAi#53]
Eu, como usuário, desejo buscar locais próximos a faculdade para saber qual vai satisfazer melhor minha necessidade.
----

### Critérios de Aceitação

- [x] Implementar uma barra de busca que estará disponível na parte superior da interface do aplicativo.
- [ ] Implementar um filtro de busca, um botão do lado da barra de busca que dará ao usuário a possibilidade de escolher entre categorias de busca(bar, lanchonete...).
- [x] Está de acordo com o manual de identidade visual.
- [x] Está de acordo com o protótipo.
- [ ] Mantém a cobertura de código acima de 90%.
- [ ] Atualização da documentação.

**Comment by zarbielli** [comment]
Precisamos editar o segundo critério de aceitação!

**Comment by GabrielDVpereira** [comment]
@zarbielli Se eu não me engano isso saiu do escopo

**Comment by zarbielli** [comment]
@GabrielDVpereira Exatamente !
