### ISSUE TITLE
US5 - Comentar Local

### ISSUE THREAD

**Issue by zarbielli** [fga-eps-mds/2018.2-IndicaAi#58]
Eu como usuário desejo iserir comentários sobre o local para falar algo que acrescente informação sobre o mesmo.
----

### Criterios de Aceitação

- [ ] Criar um campo de comentário, exibido quando o usuário pressionar o local desejado no mapa junto a outras informações.
- [ ] Criar um botão "Enviar"
- [ ] Está de acordo com o manual de identidade visual
- [ ] Está de acordo com o protótipo
- [ ] Mantém a cobertura de código acima de 90%
- [ ] Atualização da documentação

**Comment by WeillerFernandes** [comment]
Funcionalidade de comentários removida do escopo.
