### ISSUE TITLE
US7 - Ler comentários

### ISSUE THREAD

**Issue by GabrielDVpereira** [fga-eps-mds/2018.2-IndicaAi#59]
Eu como usuário desejo ler comentários para saber a opinião de pessoas que já foram ao local de meu interesse.
----

### Criterios de Aceitação

- [ ] Um botão "Visualizar Comentários ", localizado junto com o campo de informações do local, que redireciona à aba de comentários sobre o mesmo.
- [ ] Está de acordo com o manual de identidade visual
- [ ] Está de acordo com o protótipo
- [ ] Mantém a cobertura de código acima de 90%
- [ ] Atualização da documentação

**Comment by WeillerFernandes** [comment]
Funcionalidade de comentários removida do escopo.
