### ISSUE TITLE
US9 - Avaliar comentário

### ISSUE THREAD

**Issue by matheusgomesf** [fga-eps-mds/2018.2-IndicaAi#61]
Eu como usuario desejo avaliar um comentário sobre este local para dizer se este comentário é útil.
----

### Criterios de Aceitação

- [ ] Ao visualizar local
- [ ] Implementar no comentário um botão de adcionar avaliação negativa
- [ ] Implementar no comentário um botão de adcionar avaliação positiva
- [ ] No botão de avaliação positiva e negativa, adicionar a quantidade de avaliações de cada tipo
- [ ] Está de acordo com o manual de identidade visual
- [ ] Está de acordo com o protótipo
- [ ] Mantém a cobertura de código acima de 90%
- [ ] Atualização da documentação

**Comment by WeillerFernandes** [comment]
Funcionalidade de comentários removida do escopo.
