### ISSUE TITLE
Buscar locais por nome (Backend)

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/2018.2-IndicaAi#86]
### Critérios de Aceitação

- [x] Receber um nome na requisição e retornar locais registrados com esse nome.
- [ ] Mantém a cobertura de código acima de 90%.
- [x] Atualização da documentação.

**Comment by heronsousa** [comment]
sudo docker ps. 
Obs.: ps só aparece os containers que estão rodando

**Comment by heronsousa** [comment]
sudo docker exec -it (num container) bash

**Comment by mendesiasmin** [comment]
Essa feature foi aceita sem levar em consideração a cobertura de testes por a equipe de desenvolvimento ainda não havia recebido o treinamento de testes.
