### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-IndicaAi#88]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# IndicaAi

- ## *Issues*

#### **Comunicação**

Vocês estão não estão se comunicando muito bem nas *issues*.

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês estão utilizando bem as pontuações nas *issues*, aqui tem alguns links pra ajudar vocês ainda mais nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com bons nomes. É interessante a prática de padronizar os nomes, e vocês já fazem utilizando os verbos no infinitivo (que já seria a minha recomendação). Está tudo bem claro e simples como deve ser.

#### ***Labels***

As Labels estão um pouco "pobres", mas é normal para essa primeira etapa do projeto. Provavelmente eu faça um mini-guia para ajudar grupos que estão mal nisso, e consequentemente vai ajudar vocês!.

As issues de vocês estão bem nomeadas, bem explicativas, parabéns! Só precisam melhorar um pouco na comunicação e nas labels (◕‿◕✿)

- ## Documentação

#### **Documento de Visão**

O documento de visão de vocês está bem claro em mostrar o que é o problema, seus desdobramentos, e a forma de atuação do IndicaAi nesse problema.
Cumpre a função, está bem organizado, escrito e detalhado.

#### **Documento de Arquitetura**

O documento de arquitetura bom no geral, senti a falta de um maior detalhamento no diagrama do react-native(a Carla cobrou isso no meu semestre).
Ah, o link pro documento de arquitetura do gitpages está quebrado.

#### **Documentação Geral**

Senti certa dificuldade de achar no repositório a documentação de vocês. Mas no gitpages tá ótima! Fácil de encontrar e bem feita.

- ## Considerações Finais

Vocês estão bem! Muito legal que o README de vocês já tem uma explicação sobre o projeto(acho que o único até agora).
Só precisam corrigir alguns errinhos nas issues, mas estão no caminho certo! ◕‿◕

A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by zarbielli** [comment]
Show! Obrigado pelo feedback
